var grammars = [
    { "NLv": 'N2', "Nid": 1, "LNid": '', "Text": "際（に）～際（は）" },
    { "NLv": 'N2', "Nid": 2, "LNid": '', "Text": "に際してに・～にあたって" },
    { "NLv": 'N2', "Nid": 3, "LNid": '', "Text": "たとたん（に）" },
    { "NLv": 'N2', "Nid": 4, "LNid": '', "Text": "（か）と思うと・～（か）と思ったら" },
    { "NLv": 'N2', "Nid": 5, "LNid": '', "Text": "か～ないかのうちに" },
    { "NLv": 'N2', "Nid": 6, "LNid": '', "Text": "最中だ" },
    { "NLv": 'N2', "Nid": 7, "LNid": '', "Text": "うちに" },
    { "NLv": 'N2', "Nid": 8, "LNid": '', "Text": "ばかりだ・～一方だ" },
    { "NLv": 'N2', "Nid": 9, "LNid": '', "Text": "「よ」うとしている" },
    { "NLv": 'N2', "Nid": 10, "LNid": '', "Text": "つつある" },
    { "NLv": 'N2', "Nid": 11, "LNid": '', "Text": "つつ" },
    { "NLv": 'N2', "Nid": 12, "LNid": '', "Text": "てはじめて" },
    { "NLv": 'N2', "Nid": 13, "LNid": '', "Text": "上で" },
    { "NLv": 'N2', "Nid": 14, "LNid": '', "Text": "次第" },
    { "NLv": 'N2', "Nid": 15, "LNid": '', "Text": "て以来・～てこのかた" },
    { "NLv": 'N2', "Nid": 16, "LNid": '', "Text": "てからでないと・～てからでなければ" },
    { "NLv": 'N2', "Nid": 17, "LNid": '', "Text": "をはじめて（として）" },
    { "NLv": 'N2', "Nid": 18, "LNid": '', "Text": "からして" },
    { "NLv": 'N2', "Nid": 19, "LNid": '', "Text": "にわたって" },
    { "NLv": 'N2', "Nid": 20, "LNid": '', "Text": "を通じて・～を通して" },
    { "NLv": 'N2', "Nid": 21, "LNid": '', "Text": "だけ" },
    { "NLv": 'N2', "Nid": 22, "LNid": '', "Text": "限り" },
    { "NLv": 'N2', "Nid": 23, "LNid": '', "Text": "に限らず" },
    { "NLv": 'N2', "Nid": 24, "LNid": '', "Text": "のみならず" },
    { "NLv": 'N2', "Nid": 25, "LNid": '', "Text": "ばかりか" },
    { "NLv": 'N2', "Nid": 26, "LNid": '', "Text": "はもとより" },
    { "NLv": 'N2', "Nid": 27, "LNid": '', "Text": "上（に）" },
    { "NLv": 'N2', "Nid": 28, "LNid": '', "Text": "に関して" },
    { "NLv": 'N2', "Nid": 29, "LNid": '', "Text": "をめぐって" },
    { "NLv": 'N2', "Nid": 30, "LNid": '', "Text": "にかけては" },
    { "NLv": 'N2', "Nid": 31, "LNid": '', "Text": "にたいして" },
    { "NLv": 'N2', "Nid": 32, "LNid": '', "Text": "にこたえて" },
    { "NLv": 'N2', "Nid": 33, "LNid": '', "Text": "をもとに（して）" },
    { "NLv": 'N2', "Nid": 34, "LNid": '', "Text": "に基づいて" },
    { "NLv": 'N2', "Nid": 35, "LNid": '', "Text": "に沿って" },
    { "NLv": 'N2', "Nid": 36, "LNid": '', "Text": "のもとで・～のもとに" },
    { "NLv": 'N2', "Nid": 37, "LNid": '', "Text": "向けだ" },
    { "NLv": 'N2', "Nid": 38, "LNid": '', "Text": "につれて・～にしたがって" },
    { "NLv": 'N2', "Nid": 39, "LNid": '', "Text": "に伴って・～とともに" },
    { "NLv": 'N2', "Nid": 40, "LNid": '', "Text": "次第だ" },
    { "NLv": 'N2', "Nid": 41, "LNid": '', "Text": "に応じて におうじて" },
    { "NLv": 'N2', "Nid": 42, "LNid": '', "Text": "につけて" },
    { "NLv": 'N2', "Nid": 43, "LNid": '', "Text": "やら～やら" },
    { "NLv": 'N2', "Nid": 44, "LNid": '', "Text": "というか～というか" },
    { "NLv": 'N2', "Nid": 45, "LNid": '', "Text": "にしても～にしても・～にしろ～にしろ・～にせよ～にせよ" },
    { "NLv": 'N2', "Nid": 46, "LNid": '', "Text": "といった" },
    { "NLv": 'N2', "Nid": 47, "LNid": '', "Text": "を問わず" },
    { "NLv": 'N2', "Nid": 48, "LNid": '', "Text": "にかかわりなく・～にかかわらず" },
    { "NLv": 'N2', "Nid": 49, "LNid": '', "Text": "もかまわず" },
    { "NLv": 'N2', "Nid": 50, "LNid": '', "Text": "はともかく（として）" },
    { "NLv": 'N2', "Nid": 51, "LNid": '', "Text": "はさておき" },
    { "NLv": 'N2', "Nid": 52, "LNid": '', "Text": "わけがない 全部否定" },
    { "NLv": 'N2', "Nid": 53, "LNid": '', "Text": "わけではない・～というわけではない" },
    { "NLv": 'N2', "Nid": 54, "LNid": '', "Text": "ものか" },
    { "NLv": 'N2', "Nid": 55, "LNid": '', "Text": "どころではない・～どころか" },
    { "NLv": 'N2', "Nid": 56, "LNid": '', "Text": "というものではない・～というものでもない" },
    { "NLv": 'N2', "Nid": 57, "LNid": '', "Text": "とは" },
    { "NLv": 'N2', "Nid": 58, "LNid": '', "Text": "といえば" },
    { "NLv": 'N2', "Nid": 59, "LNid": '', "Text": "というと・～といえば・～といったら" },
    { "NLv": 'N2', "Nid": 60, "LNid": '', "Text": "（のこと）となると" },
    { "NLv": 'N2', "Nid": 61, "LNid": '', "Text": "といったら" },
    { "NLv": 'N2', "Nid": 62, "LNid": '', "Text": "にもかかわらず" },
    { "NLv": 'N2', "Nid": 63, "LNid": '', "Text": "ものの・～とはいうものの" },
    { "NLv": 'N2', "Nid": 64, "LNid": '', "Text": "ながら（も）＝けれども・が" },
    { "NLv": 'N2', "Nid": 65, "LNid": '', "Text": "つつ（も）" },
    { "NLv": 'N2', "Nid": 66, "LNid": '', "Text": "といっても" },
    { "NLv": 'N2', "Nid": 67, "LNid": '', "Text": "からといって" },
    { "NLv": 'N2', "Nid": 68, "LNid": '', "Text": "としたら・とすれば・とすると・となったら・となれば・となると" },
    { "NLv": 'N2', "Nid": 69, "LNid": '', "Text": "ものなら" },
    { "NLv": 'N2', "Nid": 70, "LNid": '', "Text": "（よ）うものなら" },
    { "NLv": 'N2', "Nid": 71, "LNid": '', "Text": "ないことには" },
    { "NLv": 'N2', "Nid": 72, "LNid": '', "Text": "を抜きにしては　ぬき" },
    { "NLv": 'N2', "Nid": 73, "LNid": '', "Text": "としても・〜にしても・〜にしろ・〜にせよ" },
    { "NLv": 'N2', "Nid": 74, "LNid": '', "Text": "によって" },
    { "NLv": 'N2', "Nid": 75, "LNid": '', "Text": "ものだから・～もので・～もの" },
    { "NLv": 'N2', "Nid": 76, "LNid": '', "Text": "おかげだ + 好・～せいだ + 不好" },
    { "NLv": 'N2', "Nid": 77, "LNid": '', "Text": "あまり・あまりの～に" },
    { "NLv": 'N2', "Nid": 78, "LNid": '', "Text": "につき" },
    { "NLv": 'N2', "Nid": 79, "LNid": '', "Text": "にことだし" },
    { "NLv": 'N2', "Nid": 80, "LNid": '', "Text": "のことだから" },
    { "NLv": 'N2', "Nid": 81, "LNid": '', "Text": "だけに" },
    { "NLv": 'N2', "Nid": 82, "LNid": '', "Text": "ばかりに" },
    { "NLv": 'N2', "Nid": 83, "LNid": '', "Text": "からには・～以上（は）・～上は" },
    { "NLv": 'N2', "Nid": 84, "LNid": '', "Text": "がたい" },
    { "NLv": 'N2', "Nid": 85, "LNid": '', "Text": "かねる" },
    { "NLv": 'N2', "Nid": 86, "LNid": '', "Text": "得る・～得ない" },
    { "NLv": 'N2', "Nid": 87, "LNid": '', "Text": "わけにはいかない・～わけにもいかない" },
    { "NLv": 'N2', "Nid": 88, "LNid": '', "Text": "ようがない" },
    { "NLv": 'N2', "Nid": 89, "LNid": '', "Text": "どころではない" },
    { "NLv": 'N2', "Nid": 90, "LNid": '', "Text": "わりに（は）" },
    { "NLv": 'N2', "Nid": 91, "LNid": '', "Text": "にしては" },
    { "NLv": 'N2', "Nid": 92, "LNid": '', "Text": "だけ（のことは）ある・～だけあって・～だけに" },
    { "NLv": 'N2', "Nid": 93, "LNid": '', "Text": "として" },
    { "NLv": 'N2', "Nid": 94, "LNid": '', "Text": "にとって" },
    { "NLv": 'N2', "Nid": 95, "LNid": '31', "Text": "に対して" },
    { "NLv": 'N2', "Nid": 96, "LNid": '', "Text": "にしたら・～にすれば～にしてみれば・～にしても" },
    { "NLv": 'N2', "Nid": 97, "LNid": '', "Text": "たところ" },
    { "NLv": 'N2', "Nid": 98, "LNid": '', "Text": "きり" },
    { "NLv": 'N2', "Nid": 99, "LNid": '', "Text": "あげく" },
    { "NLv": 'N2', "Nid": 100, "LNid": '', "Text": "すえ（に）" },
    { "NLv": 'N2', "Nid": 101, "LNid": '', "Text": "ところだった" },
    { "NLv": 'N2', "Nid": 102, "LNid": '', "Text": "ずじまいだ" },
    { "NLv": 'N2', "Nid": 103, "LNid": '', "Text": "ぐらい・～くらい" },
    { "NLv": 'N2', "Nid": 104, "LNid": '', "Text": "など～なんか～なんて" },
    { "NLv": 'N2', "Nid": 105, "LNid": '', "Text": "さえ" },
    { "NLv": 'N2', "Nid": 106, "LNid": '', "Text": "まで～までして～てまで" },
    { "NLv": 'N2', "Nid": 107, "LNid": '', "Text": "てでも" },
    { "NLv": 'N2', "Nid": 108, "LNid": '', "Text": "として～ない" },
    { "NLv": 'N2', "Nid": 109, "LNid": '', "Text": "とみえる" },
    { "NLv": 'N2', "Nid": 110, "LNid": '', "Text": "かねない" },
    { "NLv": 'N2', "Nid": 111, "LNid": '', "Text": "おそれがある" },
    { "NLv": 'N2', "Nid": 112, "LNid": '', "Text": "まい /～ではあるまいか" },
    { "NLv": 'N2', "Nid": 113, "LNid": '', "Text": "に違いない～に相違ない" },
    { "NLv": 'N2', "Nid": 114, "LNid": '', "Text": "にきまっている" },
    { "NLv": 'N2', "Nid": 115, "LNid": '', "Text": "ものだ" },
    { "NLv": 'N2', "Nid": 116, "LNid": '', "Text": "というものだ" },
    { "NLv": 'N2', "Nid": 117, "LNid": '', "Text": "にすぎない" },
    { "NLv": 'N2', "Nid": 118, "LNid": '', "Text": "にほかならない" },
    { "NLv": 'N2', "Nid": 119, "LNid": '', "Text": "に越したことはない" },
    { "NLv": 'N2', "Nid": 120, "LNid": '', "Text": "しかない・～よりほかない" },
    { "NLv": 'N2', "Nid": 121, "LNid": '', "Text": "べきだ・～べきではない" },
    { "NLv": 'N2', "Nid": 122, "LNid": '', "Text": "（よ）うではないか" },
    { "NLv": 'N2', "Nid": 123, "LNid": '', "Text": "ことだ" },
    { "NLv": 'N2', "Nid": 124, "LNid": '', "Text": "ものだ・ものではない" },
    { "NLv": 'N2', "Nid": 125, "LNid": '', "Text": "ことはない" },
    { "NLv": 'N2', "Nid": 126, "LNid": '', "Text": "まい・～（よ）うか～まいか" },
    { "NLv": 'N2', "Nid": 127, "LNid": '', "Text": "ものか" },
    { "NLv": 'N2', "Nid": 128, "LNid": '', "Text": "てしかたがない・てしょうがない・てたまらない" },
    { "NLv": 'N2', "Nid": 129, "LNid": '', "Text": "てならない" },
    { "NLv": 'N2', "Nid": 130, "LNid": '', "Text": "ないではいられない・ずにはいられない" },
    { "NLv": 'N2', "Nid": 131, "LNid": '', "Text": "ないわけに（は）いかない" },
    { "NLv": 'N2', "Nid": 132, "LNid": '', "Text": "ざるを得ない" },
    { "NLv": 'N2', "Nid": 133, "LNid": '', "Text": "ものだ" },
    { "NLv": 'N2', "Nid": 134, "LNid": '', "Text": "たいものだ・てほしいものだ" },
    { "NLv": 'N2', "Nid": 135, "LNid": '', "Text": "ないもの（だろう）か" },
    { "NLv": 'N2', "Nid": 136, "LNid": '', "Text": "ものがある" },
    { "NLv": 'N2', "Nid": 137, "LNid": '', "Text": "ことだ" },
    { "NLv": 'N2', "Nid": 138, "LNid": '', "Text": "ことだろう～ことか" },
    { "NLv": 'N2', "Nid": 139, "LNid": '', "Text": "において" },
    { "NLv": 'N2', "Nid": 140, "LNid": '', "Text": "に先立ってさきだつ" },
    { "NLv": 'N2', "Nid": 141, "LNid": '', "Text": "とはいいながら" },
    { "NLv": 'N2', "Nid": 142, "LNid": '', "Text": "からすると　　からというと" },
    { "NLv": 'N2', "Nid": 143, "LNid": '', "Text": "こと" },
    { "NLv": 'N2', "Nid": 144, "LNid": '', "Text": "ことなく" },
    { "NLv": 'N2', "Nid": 145, "LNid": '', "Text": "ことに" },
    { "NLv": 'N2', "Nid": 146, "LNid": '', "Text": "～ことは～が" },
    { "NLv": 'N2', "Nid": 147, "LNid": '', "Text": "ということだ　とのことだ" },
    { "NLv": 'N2', "Nid": 148, "LNid": '', "Text": "わけだ　というわけだ" },
    { "NLv": 'N2', "Nid": 149, "LNid": '', "Text": "ところから　ことから" },
    { "NLv": 'N2', "Nid": 150, "LNid": '', "Text": "～だの～だの" },
    { "NLv": 'N2', "Nid": 151, "LNid": '', "Text": "のみ" },

    // { "NLv": 'N5', "Nid": 1, "LNid": '', "Text": "できる" },
    // { "NLv": 'N5', "Nid": 2, "LNid": '', "Text": "ある" },
    // { "NLv": 'N5', "Nid": 3, "LNid": '', "Text": "いる" },
    // { "NLv": 'N5', "Nid": 4, "LNid": '', "Text": "いくつ" },
    // { "NLv": 'N5', "Nid": 5, "LNid": '', "Text": "いつ" },
    // { "NLv": 'N5', "Nid": 6, "LNid": '', "Text": "誰・どの人・どなた・どの方" },
    // { "NLv": 'N5', "Nid": 7, "LNid": '', "Text": "どう・いかが" },
    // { "NLv": 'N5', "Nid": 8, "LNid": '', "Text": "どのぐらい・どれぐらい" },
    // { "NLv": 'N5', "Nid": 9, "LNid": '', "Text": "何" },
    // { "NLv": 'N5', "Nid": 10, "LNid": '', "Text": "なぜ・どして・なんで" },
    // { "NLv": 'N5', "Nid": 11, "LNid": '', "Text": "から" },
    // { "NLv": 'N5', "Nid": 12, "LNid": '', "Text": "で" },
    // { "NLv": 'N5', "Nid": 13, "LNid": '', "Text": "と" },
    // { "NLv": 'N5', "Nid": 14, "LNid": '', "Text": "に" },
    // { "NLv": 'N5', "Nid": 15, "LNid": '', "Text": "の" },
    // { "NLv": 'N5', "Nid": 16, "LNid": '', "Text": "へ" },
    // { "NLv": 'N5', "Nid": 17, "LNid": '', "Text": "まで" },
    // { "NLv": 'N5', "Nid": 18, "LNid": '', "Text": "を" },
    // { "NLv": 'N5', "Nid": 19, "LNid": '', "Text": "や、や、など" },
    // { "NLv": 'N5', "Nid": 20, "LNid": '', "Text": "か" },
    // { "NLv": 'N5', "Nid": 22, "LNid": '', "Text": "か" },

];
function getGrammarsData(lv, isUp) {
    if (lv === '') {
        return grammars;
    } else if (lv === 5) {
        return grammars.filter(x => x.NLv === 'N' + lv);
    }
    else if (isUp === undefined) {
        return grammars.filter(x => x.NLv === 'N' + lv);
    }
    else if (isUp === 'on') {
        var array = [1, 2, 3, 4, 5];
        var f_arr = array.filter(x => x >= array[lv - 1]);
        var data = [];
        f_arr.forEach(item => {
            var tt = grammars.filter(x => x.NLv === 'N' + item);
            data.push(...tt);
        })
        return data;
    }
}
